### ISSUE TITLE
window.Zone Already Defined by Other Library

### ISSUE THREAD

**Issue by stevewithington** [angular/zone.js#1237] opened 2019-05-28 19:51 UTC
I'm including an Angular application within an existing **ASP.NET Web Forms** application. My primary issue is that the dotnet `WebFormsJS` scripts have already defined `window.Zone`.

![image](https://user-images.githubusercontent.com/251648/58507323-1d95b880-8157-11e9-8d2c-94fe42f1ca99.png)

Loading the Angular application would obviously generate the error `Uncaught Error: Zone already loaded.`

![image](https://user-images.githubusercontent.com/251648/58507354-32724c00-8157-11e9-865c-5152f634ad1e.png)

At this point, the only way I've been able to get around this is to set `window.Zone = null` just before loading the Angular script files.

![image](https://user-images.githubusercontent.com/251648/58507409-57ff5580-8157-11e9-88ee-c4930658ff5a.png)

**Is there a way to either change the scope of `Zone` or possibly rename it so that Angular can still use it?**

**Comment by JiaLiPassion** [comment] 2019-05-29 01:33
@stevewithington, which version are you using? the newest version (0.9.1) should work

**Comment by stevewithington** [comment] 2019-05-29 03:09
@JiaLiPassion, after updating to `0.9.1` from `0.8.26` (as required by `@angular/core@7.2.15`), I'm still seeing this issue.

**Comment by JiaLiPassion** [comment] 2019-05-29 03:22
Could you post a reproduce repo? thanks

**Comment by stevewithington** [comment] 2019-05-29 10:49
@JiaLiPassion,

Sure thing: <https://github.com/stevewithington/ng-dotnet-webforms>

* [Angular App](https://github.com/stevewithington/ng-dotnet-webforms/tree/master/BareBones/NgApp)
* [`package.json` reflecting `zone.js@0.9.1`](https://github.com/stevewithington/ng-dotnet-webforms/blob/0611b1e3572a625e83e26eb9b30e865cfba9d404/BareBones/NgApp/package.json#L25)
* [App running inside of dotnet](https://github.com/stevewithington/ng-dotnet-webforms/blob/0611b1e3572a625e83e26eb9b30e865cfba9d404/BareBones/About.aspx#L9-L19)

Let me know if there's anything else I can do to help.

Thanks!

**Comment by JiaLiPassion** [comment] 2019-06-01 16:27
@stevewithington, sorry for the late reply, because `zone.js` also register to the global object `window.Zone`, so if other library use the name of `Zone` already, this issue will occur.

And we have plan to make `zone` a scoped object, but it will take some time to develop, so for now, your walkaround (set `window.Zone = null`) is a reasonable solution. `rename` will not work, because `angular` will use `Zone` directly.

**Comment by stevewithington** [comment] 2019-06-01 18:09
@JiaLiPassion, I realize this may fall more on the Angular side of things, however what if we could possibly pass in a custom `zone` object to `ngZone`? This could solve the issue by essentially allowing us to rename `zone.js` and then pass it in.

For example, Angular currently only allows for either `zone.js` or `noop`. Would be great if we could do this:

```typescript
// src/app/polyfills.ts
import * as myZone from 'zone.js/dist/zone';
```

```typescript
// src/app/main.ts
platformBrowserDynamic()
    .bootstrapModule(AppModule, {
        ngZone: myZone
    });
```

I'm just concerned about side effects setting of using `windowZone = null`.

**Comment by JiaLiPassion** [comment] 2019-07-19 14:21
@stevewithington, yeah, I know, make `Zone` a module instead of a `global` object will be better, but this will bring a lot of changes to the current ecosystem. So please wait for the developing scoped zone feature. Thanks!

**Comment by JiaLiPassion** [comment] 2019-07-20 23:23
I will close this one for now because until we decide to make a `scoped zone`, this issue will not be able to be fixed.

**Closed by JiaLiPassion** 2019-07-20 23:23 UTC
