### ISSUE TITLE
IE10 is very slow on 0.8.4

### ISSUE THREAD

**Issue by prystoynyy** [angular/zone.js#691] opened 2017-03-21 13:58 UTC
I have got this problem when upgrade zone.js from 0.7.2 to 0.8.4

IE is very slow through function `attachZoneAndRemoveInternalZoneFrames(error)`

<img width="628" alt="screen shot 2017-03-21 at 3 52 07 pm" src="https://cloud.githubusercontent.com/assets/3397684/24150433/674a0dc4-0e4e-11e7-8e44-1f428057337c.png">

**Comment by JiaLiPassion** [comment] 2017-03-21 14:00
@prystoynyy , thank for posting the issue, we are discussing this issue now.

**Comment by AndriiDidkivsky** [comment] 2017-03-21 14:34
Have same issue with IE.

**Comment by YevheniiKasian** [comment] 2017-03-21 14:40
Hi all, same problem.

**Comment by sod** [comment] 2017-03-22 09:52
Might have been fixed in 0.8.5 / https://github.com/angular/zone.js/pull/690

**Comment by JiaLiPassion** [comment] 2017-03-22 09:53
yes, it has been fixed in 0.8.5

**Comment by prystoynyy** [comment] 2017-03-22 10:47
Sorry, but it hasn't been fixed. IE still very slow.

![screen shot 2017-03-22 at 12 40 29 pm](https://cloud.githubusercontent.com/assets/3397684/24194001/faa95788-0efc-11e7-8c18-3678cfecccd0.png)

**Comment by JiaLiPassion** [comment] 2017-03-22 10:54
@prystoynyy , I will do some test, now the source has been rollback to the version as the same as 
0.7.x, so the performance should be same as before.

**Comment by JiaLiPassion** [comment] 2017-03-22 12:14
@prystoynyy , could you post your test repository?

**Comment by Ks89** [comment] 2017-03-25 13:23
Hi.
I have exactly the same problem with IE 11 and Angular 4.0.0.

I can't share my code, because it's copyrighted, but I can share these screenshots:

### Debug mode

![debug interface](https://cloud.githubusercontent.com/assets/6057207/24322512/e28a9836-1165-11e7-96b0-e71c9b513137.jpg)
![debug_profiler](https://cloud.githubusercontent.com/assets/6057207/24322513/e41af3d0-1165-11e7-8323-dcc5e28d28d6.jpg)

### Production mode

![production](https://cloud.githubusercontent.com/assets/6057207/24322517/f02d6748-1165-11e7-87fd-d505fab28949.png)

As you can see, the first photo shows a weird behaviour. The second one shows a huge impact over performances. 75 seconds :( 

The funny thing is that it is happening only if Angular is running in debug mode. With production or production+aot everything is ok (photo 3) and it is quite fast.

This problem happens while starting my application, but also at every page change.

**Comment by Ks89** [comment] 2017-03-25 13:27
It can be related to this #698
I'm not sure, it's only an idea. :)

**Comment by JiaLiPassion** [comment] 2017-03-25 13:57
@Ks89 ,  if in Debug mode, remove long-stack-trace-zone.js from polyfill.ts, can you check the performance result?

**Comment by Ks89** [comment] 2017-03-25 13:58
@JiaLiPassion Ok.
I'll check Monday morning, because at the moment I cannot access to the source code.

**Comment by JiaLiPassion** [comment] 2017-03-25 15:10
@Ks89, sure, thank you.

**Comment by Ks89** [comment] 2017-03-27 07:06
@JiaLiPassion Hi!
I confirm that commenting these lines everything will be ok:

```
// Error['stackTraceLimit'] = Infinity;
// require('zone.js/dist/long-stack-trace-zone');
```

**Comment by JiaLiPassion** [comment] 2017-03-27 08:32
@Ks89 , thank you very much, long-stack-trace will have some performance cost, because it will record all stack traces occurs in every async operation even no error occurs.
we will continue to make long-stack-trace faster. 

now you can 

1. for development, you can turn long-stack-trace on, it will help to find the origin of the error.
2. for performance test, turn it off
3. for production, it should be off automatically( not included in polyfills).

**Comment by Ks89** [comment] 2017-03-27 08:54
@JiaLiPassion 
Ok, thank u.

My problem is that it is so slow that I have to disable always long-stack-trace (as you can see from my screenshot, it's requiring about 75 seconds to load my application), because it's impossibile to develop in this situation.

Why with Angular 2 and older versions of zone.js it was working without this issue?

**Comment by JiaLiPassion** [comment] 2017-03-27 08:57
@Ks89, 

> Why with Angular 2 and older versions of zone.js it was working without this issue?

do you know which version it is ?
 and you are using the zone.js 0.8.5 now, is that right?

**Comment by Ks89** [comment] 2017-03-27 12:08
Now I'm using Angular 4.0.0 and zone.js 0.8.5 and I have that problem.

With Angular 2.4.10 and zone.js 0.7.2 everything was ok.

With Angular 2.4.10 and zone.js 0.8.5 (I know that I shouldn't use this version with Angular 2.x.x), my application is working, but I have the same problem of Angular 4. 

So, I suppose that this problem is caused by zone.js >0.7.2.

**Comment by JiaLiPassion** [comment] 2017-03-27 13:33
@Ks89, thank you , I will do more research on it.

**Comment by olaf89** [comment] 2017-03-27 17:11
in my case this problem is appearing when updating 0.7.6 => 8.5. same case application is so slow that im unable to work with it on IE.

**Comment by JiaLiPassion** [comment] 2017-03-28 11:28
@prystoynyy , @Ks89 , @olaf89 , can you test the attached zone.js improve the performance or not (with long-stack-trace-zone.js)

**Comment by Ks89** [comment] 2017-03-28 12:47
@JiaLiPassion 
Still the same problem :(

**Comment by prystoynyy** [comment] 2017-03-28 12:50
@JiaLiPassion, attached zone.js is faster than 0.8.5, but IE still slow

**Comment by JiaLiPassion** [comment] 2017-03-28 12:50
@Ks89 ,thank you for confirming, I'll do more research, in your screenshot, is that possible to see the detail of ZoneAwareError performance data?

**Comment by JiaLiPassion** [comment] 2017-03-28 12:51
@prystoynyy , thank you, is that possible that you can provide a reproduce repository?

**Comment by prystoynyy** [comment] 2017-03-28 12:55
@JiaLiPassion, I can't provide a reproduce repository, because it's copyrighted

**Comment by Ks89** [comment] 2017-03-28 13:06
@JiaLiPassion I don't know how. IE is very bad. 
Also exporting data with the save button I obtained an useless csv with the same data of the screenshot.

**Comment by JiaLiPassion** [comment] 2017-03-28 13:08
@Ks89, ok, I see, is that possible that you can provide a reproduce repo? I don't know how to reproduce.

**Comment by JiaLiPassion** [comment] 2017-03-28 13:31
hi, guys, could you try the attached long-stack-trace-zone.js?
[long.zip](https://github.com/angular/zone.js/files/875799/long.zip)

**Comment by Ks89** [comment] 2017-03-28 13:58
@JiaLiPassion my code is copyrighted.

I tried with a personal skeleton project on IE 11 with angular 4, zone.js 0.8.5 with long stacktrace and dev mode and this problem it's happening. You are very lucky :)

To run use: 
- npm run build:dev
- cd dist
- lite-server

This is the repo:  [HERE](https://github.com/Ks89/angular-webpack-skeleton)

The situation is not so bad like in my copyrighted project,. But it is also an issue.

**Comment by JiaLiPassion** [comment] 2017-03-28 14:03
@Ks89, thank you, I will try it, can you try my previous post,https://github.com/angular/zone.js/files/875799/long.zip

**Comment by Ks89** [comment] 2017-03-28 14:20
@JiaLiPassion still happening also with long-stack-trace-zone.js

**Comment by JiaLiPassion** [comment] 2017-03-28 14:25
@Ks89, sorry, could you try this one? 
[long.zip](https://github.com/angular/zone.js/files/875975/long.zip)

**Comment by Ks89** [comment] 2017-03-28 14:41
@JiaLiPassion still the same problem
![screenshot-bug](https://cloud.githubusercontent.com/assets/6057207/24411114/52fa3484-13d5-11e7-9142-665f7721d6d6.png)

I think that you should try with my skeleton project :)

**Comment by JiaLiPassion** [comment] 2017-03-28 14:42
@Ks89, ok , I will debug with your repo more deeply, thank you for your help.

**Comment by JiaLiPassion** [comment] 2017-03-28 16:40
@KS89, I tried you repo, it is slow, but after I replaced with the modified zone.js and long-stack-trace, it is fast, and the attache is the performance screenshot, ZoneAwareError related stack is gone, could you try the attached dist folder again?

<img width="944" alt="2017-03-29 1 37 57" src="https://cloud.githubusercontent.com/assets/1442575/24416663/8886fdb2-1420-11e7-93ea-a4bcd818e204.png">


[dist.zip](https://github.com/angular/zone.js/files/876389/dist.zip)

**Comment by prystoynyy** [comment] 2017-03-28 20:35
@JiaLiPassion, thank you very much, project with attached dist folder works as with 0.7.2
Yes, it is fast

**Comment by JiaLiPassion** [comment] 2017-03-29 00:35
@prystoynyy , thank you for confirm, I will do some other modification to test and try to figure out how to modify this one better.

**Comment by JiaLiPassion** [comment] 2017-03-29 06:40
@prystoynyy , @Ks89, could you try to use the attached dist.zip to test again? I want to find out the exact problem, I tried @Ks89's repo, this version is also ok.
[dist.zip](https://github.com/angular/zone.js/files/878057/dist.zip)

**Comment by Ks89** [comment] 2017-03-29 07:00
@JiaLiPassion I confirm that now it's working.

Thank you very much.

**Comment by JiaLiPassion** [comment] 2017-03-29 07:16
@Ks89, thank for your confirmation, I will make a PR to fix this one.

**Comment by Ks89** [comment] 2017-04-10 08:14
Hi @JiaLiPassion 
Is there an official schedule for this fix?

It's really difficult to develop with this issue. I have to compile with production config also while developing. 
Thanks.

**Closed** 2017-04-10 09:04 UTC

**Comment by lelezeus88** [comment] 2017-04-20 08:03
Hi all,
with IE11 is again very slow, I have this configuration:
 {
       "@angular/animations": "4.0.0",
        "@angular/common": "4.0.0",
        "@angular/compiler": "4.0.0",
        "@angular/core": "4.0.0",
        "@angular/forms": "4.0.0",
        "@angular/http": "4.0.0",
        "@angular/material": "2.0.0-beta.3",
        "@angular/platform-browser": "4.0.0",
        "@angular/platform-browser-dynamic": "4.0.0",
        "@angular/service-worker": "^1.0.0-beta.8",
        "@angular/router": "4.0.0",
        "@angular/compiler-cli": "4.0.0",
        "core-js": "2.4.1"
        "angular2localization": "1.4.2",
        "platform": "1.3.4",
        "reflect-metadata": "0.1.10",
        "rxjs": "5.3.0"
        **"zone.js": "0.8.5"**
}
Will the fix be included in  "zone.js": "0.8.6"?
Thanks.

**Comment by JiaLiPassion** [comment] 2017-04-20 08:12
@lelezeus88 , yes, please wait for the 0.8.6 release, it will be released in that version, thanks!

**Comment by lelezeus88** [comment] 2017-04-20 08:16
Do you know, approximately, when will it be released?  Thanks.

**Comment by JiaLiPassion** [comment] 2017-04-20 08:17
I am not sure, but I think it will be released soon, because most high priority PR have been merged.

**Comment by bharath3719** [comment] 2018-02-22 10:59
Facing this issue due to ZoneJs. Using the version 0.8.19 . Pls help!

![zone](https://user-images.githubusercontent.com/19222968/36534524-c7bbc460-17ec-11e8-8f71-f4e9be9b7df7.png)


![image](https://user-images.githubusercontent.com/19222968/36534752-7293cf9a-17ed-11e8-8ae2-aa18d1093720.png)

**Comment by lelezeus88** [comment] 2018-02-22 11:16
try to disable LongStackTrace of zone.js

2018-02-22 11:59 GMT+01:00 bharath3719 <notifications@github.com>:

**Comment by bharath3719** [comment] 2018-02-22 11:58
Any leads on how to do the same ? New to angualr please excuse. 
I see the following code in zone.js

 if (state === REJECTED && value instanceof Error) {
                    // check if longStackTraceZone is here
                    var trace = Zone.currentTask && Zone.currentTask.data &&
                        Zone.currentTask.data[creationTrace];
                    if (trace) {
                        // only keep the long stack trace into error when in longStackTraceZone
                        ObjectDefineProperty(value, CURRENT_TASK_TRACE_SYMBOL, { configurable: true, enumerable: false, writable: true, value: trace });
                    }
                }

Removing this will disable LongStackTrace ?

**Comment by JiaLiPassion** [comment] 2018-02-22 13:47
@bharath3719 , the screenshot you take doesn't mean `zone` take a lot of time, because all `async callback` will be `invoked` in `ZoneDelegate.prototype.invokeTask`.

And in `prod` mode, `longStackTrace` is disabled by default, if you want to disable `longStackTrace` in `dev` mode, just 
- remove `import zone.js/dist/long-stack-trace-spec` from `src/test.ts` (older angular/cli project)
- remove `import 'zone.js/dist/zone-testing';` and change it to 

```javascript
import '../zone-spec/proxy';
import '../zone-spec/sync-test';
import '../jasmine/jasmine';
import '../zone-spec/async-test';
import '../zone-spec/fake-async-test';
```

**Comment by bharath3719** [comment] 2018-02-23 06:32
@JiaLiPassion  We were importing 
import 'zone.js';
import 'zone.js/dist/zone'; earlier...

I still see very low performance of application on IE after removing those and importing the files uve mentioned.
And you mean to say slowness is due to the code written and not due to zone ?
This is a currently a small application and i don't feel these many Js function calls are necessary.. right ? How do i get to the root of the problem?

![image](https://user-images.githubusercontent.com/19222968/36581064-0b51513c-1891-11e8-9292-c6f56bf88ef0.png)

New to this project and to angular as well.. will be delete this comment once u respond back :D

**Comment by JiaLiPassion** [comment] 2018-02-24 14:58
@bharath3719 , `a script has been running for too long` message is far too slow, can you post a reproduce repo? And could you test the application in other browser such as Chrome?
