### ISSUE TITLE
newest Zone.js(angular2) doesn't work with mongoose db 

### ISSUE THREAD

**Issue by medozs** [angular/zone.js#448] opened 2016-09-16 04:53 UTC
old version compilers but create other problems.
the new version displays:

c:\Users\ahmed\Documents\Me\Projects\Netbine5\node_modules\zone.js\dist\zone-node.js:129
                        throw error;
                        ^

TypeError: Cannot read property 'filter' of undefined
    at zoneAwareEventListeners (c:\Users\ahmed\Documents\Me\Projects\Netbine5\node_modules\zone.js\dist\zone-node.js:715:13)
    at Db.listeners (eval at createNamedFn (c:\Users\ahmed\Documents\Me\Projects\Netbine5\node_modules\zone.js\dist\zone-node.js:724:17), <anonymous>:3:36)
    at Server.listener (c:\Users\ahmed\Documents\Me\Projects\Netbine5\node_modules\mongodb\lib\db.js:1786:15)
    at Server.g (events.js:286:16)
    at ZoneDelegate.invokeTask (c:\Users\ahmed\Documents\Me\Projects\Netbine5\node_modules\zone.js\dist\zone-node.js:225:37)
    at Zone.runTask (c:\Users\ahmed\Documents\Me\Projects\Netbine5\node_modules\zone.js\dist\zone-node.js:125:47)
    at Server.ZoneTask.invoke (c:\Users\ahmed\Documents\Me\Projects\Netbine5\node_modules\zone.js\dist\zone-node.js:293:33)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at Server.connectHandler (c:\Users\ahmed\Documents\Me\Projects\Netbine5\node_modules\mongodb\lib\server.js:329:10)
    at Server.g (events.js:286:16)
    at ZoneDelegate.invokeTask (c:\Users\ahmed\Documents\Me\Projects\Netbine5\node_modules\zone.js\dist\zone-node.js:225:37)
    at Zone.runTask (c:\Users\ahmed\Documents\Me\Projects\Netbine5\node_modules\zone.js\dist\zone-node.js:125:47)
    at Server.ZoneTask.invoke (c:\Users\ahmed\Documents\Me\Projects\Netbine5\node_modules\zone.js\dist\zone-node.js:293:33)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)

**Comment by jvbianchi** [comment] 2016-09-18 19:29
it might be related with https://github.com/angular/universal-starter/issues/164

**Comment by Hongbo-Miao** [comment] 2016-09-19 04:06
zone.js 0.6.21 works well, the issue starts from 0.6.22

**Comment by Hongbo-Miao** [comment] 2016-09-20 22:17
After updating to latest version:

```
zone.js 0.6.25
mongoose 4.6.1
@types/mongoose 4.5.34
```

The issue is gone now.

**Comment by mhevery** [comment] 2016-10-10 17:19
@alexwolfe could you look at this. I think this may be related to the changes you have done to the node.

**Comment by alexwolfe** [comment] 2016-10-11 15:19
@mhevery Haven't made any changes to node, perhaps you meant to tag another Alex?

**Comment by mhevery** [comment] 2016-10-12 19:00
sorry wrong alex, now the right one => @alxhub

**Comment by alxhub** [comment] 2016-10-12 19:24
@mhevery yep, found the problem. Fix is in PR #485.

**Closed** 2017-09-11 17:47 UTC
