### ISSUE TITLE
Cordova pause event error from a null target

### ISSUE THREAD

**Issue by adamdbradley** [angular/zone.js#323] opened 2016-04-14 01:21 UTC
Cordova fires a `pause` event when the app is put into the background, but this error is thrown from within `patchViaCapturingAllTheEvents()`:
![image](https://cloud.githubusercontent.com/assets/452425/14514195/2745ffaa-01b4-11e6-80d5-89f9d07eca25.png)

It looks as though `event.target` is `null`:
![image](https://cloud.githubusercontent.com/assets/452425/14514226/5e29da1e-01b4-11e6-92b4-64c6eca56fe4.png)

This only happens on Cordova's `pause` event, but is not a problem with the others:
https://cordova.apache.org/docs/en/latest/cordova/events/events.html#pause

**Comment by mhevery** [comment] 2016-04-14 16:55
@juliemr could you look at this?

**Comment by juliemr** [comment] 2016-04-14 19:07
This is the easy fix: https://github.com/angular/zone.js/pull/327

But I haven't found the magical combination of steps necessary to reproduce the bug outside of cordova. @adamdbradley do you have a script to create a targetless event that I can add to our tests without setting up cordova on our CI?

This also doesn't address Zones possibly not properly including or wrapping Cordova's custom events - it just makes sure that it won't outright fail.

**Comment by adamdbradley** [comment] 2016-04-18 03:15
@juliemr I dug through cordova and it looks like the `pause` event ultimately [calls fireDocumentEvent](https://github.com/apache/cordova-js/blob/c517ca811b4948b630e0b74dbae6c9637939da24/src/cordova.js#L138)

Inside fireDocumentEvent it then uses the [createEvent method](https://github.com/apache/cordova-js/blob/c517ca811b4948b630e0b74dbae6c9637939da24/src/cordova.js#L86)

Next, it passes the created `evt` to [documentEventHandlers[type].fire(evt)](https://github.com/apache/cordova-js/blob/c517ca811b4948b630e0b74dbae6c9637939da24/src/cordova.js#L141) 

Which is cordova's [Channel.prototype.fire](https://github.com/apache/cordova-js/blob/24ab6855470f2dc0662624b597c98585e56a1666/src/common/channel.js#L198)

The `fireArgs` variable from within `Channel.prototype.fire` has the `null` `target`: 
![image](https://cloud.githubusercontent.com/assets/452425/14592783/0da37fa0-04e8-11e6-942b-2d6c80d333e7.png)

`Channel.prototype.fire` then creates and [runs each function](https://github.com/apache/cordova-js/blob/24ab6855470f2dc0662624b597c98585e56a1666/src/common/channel.js#L214) in the `toCall` array:
![image](https://cloud.githubusercontent.com/assets/452425/14592821/8d2e4b92-04e8-11e6-86a7-310f9be3e80e.png)

One of them being the callback created from within zone's `patchViaCapturingAllTheEvents()`. 

Sorry I'm not able to provide an explanation as to why cordova is calling these events like this, but hopefully this can help document where the issues are coming from, and hopefully help to create tests. Hope that helps, thanks.

**Comment by juliemr** [comment] 2016-04-19 23:28
Note that this should be fixed (with my dumb fix) in the current version, but I'm leaving this open since we still don't actually have a test to guard against it failing.

**Comment by peter-fu** [comment] 2016-05-06 15:30
The error still occurs in iOS simulator for `pause` event.

```
exeption nativeEvalAndFetch : TypeError: null is not an object (evaluating 'elt.constructor')
```

How about making it like this? (I have tried this code locally and there's no error for the `pause` event any more).

```
if (elt && elt.constructor) {
  source = elt.constructor['name'] + '.' + onproperty;
} else {
  source = 'unknown.' + onproperty;
}
```

I'm using Ionic 2 beta, this error can be reproduced in all Ionic 2 beta projects.

```
$ ionic info

Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6-201604261740
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.3.2
Xcode version: Xcode 7.3.1 Build version 7D1014 
```

However, I didn't observe such error with the HelloWorld project created by Cordova followed by this article - http://cordova.apache.org/docs/en/latest/guide/cli/index.html. So I am not sure where the root cause of the problem locates.

**Closed** 2019-07-21 14:41 UTC
