### ISSUE TITLE
Implement electron-zone 

### ISSUE THREAD

**Issue by robwormald** [angular/zone.js#537] opened 2016-12-11 12:48 UTC
Electron uses both browser and some node APIs (EventEmitter, etc), and events fired by electron APIs (MenuItem, for example) cause angular to drop out the zone. Ref https://github.com/angular/angular/issues/13363

We should implement an electron zone patch, that combines the browser APIs as well as a subset of the node APIs available to electron.

**Comment by JiaLiPassion** [comment] 2016-12-11 13:24
I tried the issue in this [repo](https://github.com/pamtbaau/ng2-webpack-electron-menu-routing-failing-change-detection), but can't reproduce. But I think current zone.js did not patch browser and node.js at the same time, just like #524 maybe the same issue in electron. Could you provide a reproduce step?

**Comment by robwormald** [comment] 2016-12-11 13:25
@JiaLiPassion navigate via the menu at the top of the screen:
<img width="522" alt="screen shot 2016-12-11 at 10 25 07 pm" src="https://cloud.githubusercontent.com/assets/534930/21080374/b3c20e92-bff0-11e6-94bf-549f0c02c35d.png">

**Comment by JiaLiPassion** [comment] 2016-12-11 13:26
@robwormald Yes, I did that , and the page just switched and click to increase value works.

**Comment by sittingbool** [comment] 2017-01-20 13:50
any update on this? i can use angular 2 only up to version 2.1 so far with electron

**Comment by JiaLiPassion** [comment] 2017-01-20 14:22
For now, you have to do like this 

```javascript
 let pageMenu = new MenuItem({
            label: 'Page',
            submenu: [
                { label: 'Page 1', click: Zone.current.wrap(() => this.router.navigate(['/page1'])) },
                { label: 'Page 2', click: Zone.current.wrap(() => this.router.navigate(['/page2'])) },
            ],
        });
```

**Comment by sittingbool** [comment] 2017-01-20 14:31
I don't only have a problem with the router. I have issues in general like with change detection and such.

**Comment by JiaLiPassion** [comment] 2017-01-20 14:49
@sittingbool, could you give an example through some sample code or repository.

**Comment by JiaLiPassion** [comment] 2017-01-22 04:40
@sittingbool , if your problem is related with electron menu or something like that, you could use the 
method just like 
```javascript
 let pageMenu = new MenuItem({
            label: 'Page',
            submenu: [
                { label: 'Page 1', click: Zone.current.wrap(() => this.router.navigate(['/page1'])) },
                { label: 'Page 2', click: Zone.current.wrap(() => this.router.navigate(['/page2'])) },
            ],
        });
```
If your problem is related with your application(not electron), you may check the #533 to see whether it is the same problem, if it is , you can check PR #608 to see whether it resolve your problem or not.

**Comment by pamtbaau** [comment] 2017-08-09 09:55
Any progress on this issue with electon menus and zone?

**Comment by sittingbool** [comment] 2017-08-09 10:12
I really would appreciate that too
I cant really use electron with Angular 2+ so far.

**Comment by pamtbaau** [comment] 2017-08-09 10:24
@sittingbool The suggested workarround of wrapping my code with `zone.run(...)` works fine for me, but I would rather do it without...

This is how my code looks like when invoking an Electron menu item:
```
private initMenu() {
   const template: Electron.MenuItemConstructorOptions[] = [
      {
          label: 'Set exchange rates',
          click: () => this.zone.run(() => this.showExchangeRateDialog = true),
      },
      {
          label: 'Set stock prices',
          click: () => this.zone.run(() => this.showStockPriceDialog = true),
      },
   ];

   this.menu = Menu.buildFromTemplate(template);
}
```

ChangeDetector is now picking up any changes of `this.showExchangeRateDialog` and `this.showStockPriceDialog` and the dialogs will show accordingly.

**Comment by sittingbool** [comment] 2017-08-09 10:30
I don't have this Issue with menu alone. I have a general Issue with the Zone- Implementation in electron. The behavior has been overwritten from the default as far as I could see and Zone.js is reacting allergic to it.

**Comment by JiaLiPassion** [comment] 2017-08-10 01:34
@pamtbaau , if it is just `menu` issue, I can make a patch to do it, but I don't know there are other cases or not.

**Comment by pamtbaau** [comment] 2017-08-10 07:26
@JiaLiPassion, So far, I've encountered the problem when setting a property inside an Electron initiated callback. E.g. a (popup)menu callback or dialog callback. I've created a [repo](https://github.com/pamtbaau/angular4-zone-electron-callback) to reproduce the three scenarios.

**Comment by daganchen** [comment] 2017-12-12 08:30
Having the same issues like @sittingbool,
all events are firing but component not rendering as expected.
I'm using Angular5, if I downgrade to version 2, issues will stop appearing?

**Comment by JiaLiPassion** [comment] 2017-12-12 09:10
@daganchen , this issue has nothing to do with angular version, I am implementing an `electron zone` now, please wait for a while.

**Comment by ameagol** [comment] 2017-12-12 14:13
Hi All, I've just found a solution that works for Angular 5 and all latest Codes for Node.js and Typescript:

Follow:
 
`npm install ngx-electron --save`

then, use the code as follow

```
import { ElectronService } from 'ngx-electron';
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router'; 


@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
 
  constructor(private _electronService: ElectronService,private router: Router) {  
    this.initMenu();
  }

  ngOnInit() {
 

  }
 
    private initMenu() {
      let menu = this._electronService.remote.Menu.getApplicationMenu();

      let pageMenu  = new this._electronService.remote.MenuItem(
        {
          label: 'Page',
              submenu: [
                  { label: 'Page 1', click: () => this.router.navigate(['/page1']) },
                  { label: 'Page 2', click: () => this.router.navigate(['/page']) },
              ],
        }
      );

      menu.insert(1, pageMenu);

      this._electronService.remote.Menu.setApplicationMenu(menu);
  
    }
}
```

**Make Sure the pages exists on routing file, otherwise will throw many route errors.**

More details check Wonderfull Lib from ThorstenHans [here](https://github.com/ThorstenHans/ngx-electron/)

**Comment by pamtbaau** [comment] 2017-12-12 17:03
@ameagol I'm not using Angular's routing,  but the above mentioned workaround works fine for the original issue. Maybe the workaround might also work in your use case, which might make the extra library a bit superfluous for an issue that will be properly fixed in due time.

I use menus in the following way:
```
...
import { remote } from 'electron';
const { Menu } = remote;

@Component({
    selector: 'main-component',
    templateUrl: 'main.component.html',
})

export class MainComponent implements OnDestroy {
    private menu: Electron.Menu;
    ...
    constructor() {
        this.initMenu();
    }

    public onMenu() {
        this.menu.popup();
    }

    private initMenu() {
        const template: Electron.MenuItemConstructorOptions[] = [
            {
                label: 'Set exchange rates',
                click: () => this.zone.run(() => this.showExchangeRateDialog = true),
            },
            {
                label: 'Set stock prices',
                click: () => this.zone.run(() => this.showStockPriceDialog = true),
            },
        ];

        this.menu = Menu.buildFromTemplate(template);
    }
}
```

**Closed** 2017-12-27 21:57 UTC

**Comment by pamtbaau** [comment] 2017-12-28 06:05
@JiaLiPassion Great news! Thanks for this zone fixup for Electron. Would love to test this out in my application. When will it be released and how should I use it?

**Comment by JiaLiPassion** [comment] 2017-12-28 15:49
@pamtbaau, thank you, I have created a sample repo to describe how to use, https://github.com/JiaLiPassion/zone-electron, please use the new release to test your application.

**Comment by pamtbaau** [comment] 2017-12-28 16:52
Maybe I have a wrong perception as to how this feature solves the electron zone issues.

The next piece of code is a declaration of a menuitem using `this.zone.run()` as workaround:
```
const template: MenuItemConstructorOptions[] = [
    {
        label: `Delete ${hero.name}`,
        click: () => this.zone.run(() => this.deleteHero(hero)),
    },
];
```
I hoped I could now simply remove the `this.zone.run()` wrapper:
```
const template: MenuItemConstructorOptions[] = [
    {
        label: `Delete ${hero.name}`,
        click: () => this.deleteHero(hero),
    },
];
```
But no luck... Without the `this.zone.run()`, changeDetection doesn't work.
Could you please give me some hints as to how a menuitem should be declared right now?

**Comment by JiaLiPassion** [comment] 2017-12-29 14:19
@pamtbaau , I have tested the `menuItem.click()`, it works, so could you check here,
https://github.com/JiaLiPassion/zone-electron/blob/master/src/app/components/home/home.component.ts#L108

and make sure 

1. you updated to `zone.js` 0.8.19
2. in your `src/polyfill.ts`, add `import 'zone.js/dist/zone-patch-electron'`.

**Comment by pamtbaau** [comment] 2017-12-29 17:22
@JiaLiPassion I have tested your suggestions, but it's not working

1. Downloaded your app: It works  
  Noticed that you are using package `git+https://github.com/JiaLiPassion/zone.js.git#electrondist`.  
  NB. When installing your package, npm returns: +zone.js 0.8.18
2. npm install --save zone.js (yields 0.8.19)  
  You app doesn't work
3. npm install --save git+https://github.com/JiaLiPassion/zone.js.git#electrondist  
  You app works...

Same with my own app. It only works when installing `git+https://github.com/JiaLiPassion/zone.js.git#electrondist`

**Comment by JiaLiPassion** [comment] 2017-12-30 04:02
@pamtbaau , thank you for your detail information, it seems `0.8.19` not release the newest contents, I will check it, please use `git+https://github.com/JiaLiPassion/zone.js.git#electrondist` for test now.

**Comment by JiaLiPassion** [comment] 2017-12-30 09:51
@pamtbaau , I have checked `0.8.19` and found  I made a typo, I will fix it and please use my branch for test by now.
