### ISSUE TITLE
Keep the native behaviour of setTimeout, i.e. returning a numerical ID of the timeout instead of a task

### ISSUE THREAD

**Issue by jahtalab** [angular/zone.js#361] opened 2016-06-13 10:51 UTC

**Comment by jahtalab** [comment] 2016-06-13 10:53
#341 #314

**Comment by henrysun918** [comment] 2016-06-15 20:18
I encountered the same issue with Angular 1.5.3 + 2.0.0 rc.1 upgradeAdapter. I'm building with node 5.11.1 and npm 3.8.6.

![image](https://cloud.githubusercontent.com/assets/1895289/16095760/f4b40f6e-32fa-11e6-98ce-b18c96273261.png)

As a result, I am seeing "digest already in progress error", and the $timeout.cancel() no longer works.

**Comment by vicb** [comment] 2016-06-15 22:32
Duplicate of #314

**Closed by vicb** 2016-06-15 22:32 UTC
