### ISSUE TITLE
Violation messages in Chrome Version 63.0.3239.84 console in Angular app

### ISSUE THREAD

**Issue by jtsom** [angular/zone.js#988] opened 2018-01-03 19:38 UTC
In recent versions of Chrome, I've started to see many "violation" messages in the Chrome console when running an Angular app (latest versions of Angular, etc.):

```
[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```

Also:

```
[Violation] 'load' handler took 314ms
```

This is a simple Angular app, that has a list of data on it, so I'm assuming it's because Chrome needs to scroll to show the whole list?

(complete message below)

```
zone.js:1662 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
customScheduleGlobal	@	zone.js:1662
ZoneDelegate.scheduleTask	@	zone.js:407
Zone.scheduleTask	@	zone.js:232
Zone.scheduleEventTask	@	zone.js:258
(anonymous)	@	zone.js:1841
addHandler	@	events_engine.js:144
(anonymous)	@	events_engine.js:349
iterateEventNames	@	events_engine.js:294
(anonymous)	@	events_engine.js:306
(anonymous)	@	events_engine.js:234
applyForEach	@	events_engine.js:58
(anonymous)	@	events_engine.js:64
initRender.each	@	renderer_base.js:545
applyForEach	@	events_engine.js:62
(anonymous)	@	events_engine.js:71
object.(anonymous function)	@	dependency_injector.js:24
setup	@	wheel.js:20
strategy.(anonymous function)	@	event_registrator.js:30
callMethod	@	events_engine.js:48
addHandler	@	events_engine.js:140
(anonymous)	@	events_engine.js:349
iterateEventNames	@	events_engine.js:294
(anonymous)	@	events_engine.js:306
(anonymous)	@	events_engine.js:234
applyForEach	@	events_engine.js:58
(anonymous)	@	events_engine.js:71
object.(anonymous function)	@	dependency_injector.js:24
(anonymous)	@	events_engine.js:473
(anonymous)	@	events_engine.js:234
applyForEach	@	events_engine.js:58
eventsEngine.subscribeGlobal	@	events_engine.js:471
_attachHandlers	@	emitter_registrator.js:34
ctor	@	emitter_registrator.js:25
inheritor	@	class.js:95
(anonymous)	@	emitter_registrator.js:190
../../../../devextreme/events/core/emitter_registrator.js	@	vendor.bundle.js:3240
__webpack_require__	@	inline.bundle.js:55
(anonymous)	@	click.js:18
../../../../devextreme/events/click.js	@	vendor.bundle.js:3208
__webpack_require__	@	inline.bundle.js:55
(anonymous)	@	accordion.js:13
../../../../devextreme/ui/accordion.js	@	vendor.bundle.js:3528
__webpack_require__	@	inline.bundle.js:55
(anonymous)	@	accordion.js:26
../../../../devextreme-angular/ui/accordion.js	@	vendor.bundle.js:384
__webpack_require__	@	inline.bundle.js:55
(anonymous)	@	index.js:26
../../../../devextreme-angular/index.js	@	vendor.bundle.js:376
__webpack_require__	@	inline.bundle.js:55
(anonymous)	@	app.module.ts:17
../../../../../src/app/app.module.ts	@	main.bundle.js:44
__webpack_require__	@	inline.bundle.js:55
(anonymous)	@	main.ts:4
../../../../../src/main.ts	@	main.bundle.js:188
__webpack_require__	@	inline.bundle.js:55
0	@	main.bundle.js:203
__webpack_require__	@	inline.bundle.js:55
webpackJsonpCallback	@	inline.bundle.js:26
(anonymous)	@	main.bundle.js:1
```

**Comment by JiaLiPassion** [comment] 2018-01-04 02:50
@jtsom , I think just like the `error message` said, you should add `wheel` event handler as `passive`. I believe it is not a `zone.js` issue.

**Comment by jtsom** [comment] 2018-01-04 03:27
I have no control over the wheel event-this is a angular cli application, of which zone.js is a built in part

**Comment by JiaLiPassion** [comment] 2018-01-04 07:33
@jtsom , I believe `zone.js` or `angular-cli` will not add `wheel` event , in your stack trace, I think maybe you should check `devextreme-angular` library. It seems this library added `wheel` event handler.

**Comment by jameskentTX** [comment] 2018-01-22 12:58
Yep, I have the same problem too. This is definitely something to solve.
It's annoying message and what is more important - is slowing down scrolling.

**Comment by JiaLiPassion** [comment] 2018-01-22 13:17
@jameskentTX , could you provide a reproduce repo?

**Comment by kevinkuszyk** [comment] 2018-01-24 11:27
I also see the following in the Chrome console:

```
zone.js:1643 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```

**Comment by JiaLiPassion** [comment] 2019-07-21 05:50
Will close this for now because there already the same issue in angular repo

**Closed by JiaLiPassion** 2019-07-21 05:50 UTC
