### ISSUE TITLE
HTMLCanvasElement.toBlob polyfill strange behavior (in angular 4)

### ISSUE THREAD

**Issue by Arikael** [angular/zone.js#867] opened 2017-08-04 07:20 UTC
Since Safari doesn't implement HTMLCanvasElement.toBlob (https://developer.mozilla.org/de/docs/Web/API/HTMLCanvasElement/toBlob) I tried to use the following polyfill -> https://github.com/blueimp/JavaScript-Canvas-to-Blob/

here's how I would call it in my code (note that I use TS)

```
const canvas: any = document.createElement('canvas');
canvas.toBlob((blob) => {
                console.log('test0');
            });
```
this fails in Safari giving the following error 
`macroTask 'HTMLCanvasElement.toBlob': can not transition to 'running', expecting state 'scheduled', was 'scheduling'.  zone.js:532`

when looking at the polyfills code it fails at the following line (first line is 77)
```
if (hasBlobConstructor) {
    return new Blob(
        [hasArrayBufferViewSupport ? intArray : arrayBuffer],
            {type: mediaType}
     )
}
```
so as soon as I want to return it (the new blob) it fails.

Since I'm still a beginner with zone.js etc I started fiddling around. Tried to run the code explicitly within and outside angulars zone. Nothing worked.

I then renamed the polyfills function name from `toBlob` to `toBlob2`  by just adding the following in the pollyfills js file
```
CanvasPrototype.toBlob2 = function (callback, type, quality) {
        callback(dataURLtoBlob(this.toDataURL(type, quality)))
    }
```

And it just started to work. Apart from the function name everything is exactly the same.

P.S. 
the error also occured with other polyfills I tried which lead me to believe it's not the polyfills problem.

is this a bug or expected behavior?
Am I just missing something?

if you need more info just tell me, thanks.

**Comment by JiaLiPassion** [comment] 2017-08-04 07:21
@Arikael , could you post a reproduce repo?

**Comment by Arikael** [comment] 2017-08-04 07:49
Here is the repo: https://plnkr.co/edit/ORMC6qP0CNVCFsbwRepm?p=preview

while constructing the repo I noticed two things
1. in my app `this.zone.hasPendingMacrotasks` returns `true `right before calling `toBlob` in the plunkr it returns `false`
this.zone = Angular's NgZone

2. In my app and also in the plunkr I first include all polyfills and then zone.js
if I switch those two statements and first include zone.js it will work in safari

**Comment by JiaLiPassion** [comment] 2017-08-04 07:57
@Arikael, How to check the result with your plunker? I use the chrome and safari, both output 
`I will work in safari` and `I will fail in Safari`

**Comment by JiaLiPassion** [comment] 2017-08-04 11:11
@Arikael , the reason is in current version of `zone.js`, we provide a patch for `toBlob` and treat it as a macroTask just like `setTimeout`, so the `callback` of toBlob will be in the `ngZone`.

your issue is , 

1. load `toBlob.js` before `zone.js ( this is correct, you should load all polyfill before zone.js)
2. error occurs.

the error is because your `toBlob` polyfill is not an async operation, `zone.js` expect that `toBlob` should be an async operation, so you need to make it async.

I have updated the plunker(I updated toBlob.js) which can work in safari.

https://plnkr.co/edit/iP5VuSDXBbDMm91woMuU?p=preview

**Comment by Arikael** [comment] 2017-08-04 11:43
thanks a lot

so I will either fork blueimp's polyfill or make a PR :)

could you give insight why loading `toBlob.js` after `zone.js` is wrong or might lead to problems?

**Comment by JiaLiPassion** [comment] 2017-08-04 13:28
@Arikael , glad to help.

load `toBlob.js` after `zone.js` will cause `callback` passed to toBlob method run in wrong zone, for example 

```javascript
canvas.toBlob(function(data) {
  // update model of angular component
  this.text = data;
});
```

if load `toBlob.js` after `zone.js`, the text may not be updated.

**Closed** 2017-08-04 13:42 UTC
