### ISSUE TITLE
Support for native async/await?

### ISSUE THREAD

**Issue by elierotenberg** [angular/zone.js#715] opened 2017-04-03 06:08 UTC
Hello,

As said in a previous issue, I'm currently working on a zone.js wrapper for Node designed to provide isolation for HTTP request handlers.

I'm working in Node 7.8, which supports native async/await.
Unless I'm doing something wrong, zone.js doesn't seem to interop nicely with native async functions.

The following piece of code:
```js
const zone = Zone.current.fork({
  name: 'test-zone',
});
zone.run(async () => {
  console.log(Zone.current.name);
  await Promise.resolve();
  console.log(Zone.current.name);
  done();
});
```
yields:
```js
test-zone
<root>
```

when using native async/await.
If I transpile the same code using `babel-transform-async-to-generator`, this yields:
```js
test-zone
test-zone
```
the latter being the wanted behavior.

Am I doing something wrong? Is native async/await supported by zone.js, and if not, are there plans to support it? (Is it even possible?)

Thanks,

**Comment by elierotenberg** [comment] 2017-04-03 06:28
After further testing, even when transpiled with babel, the example doesn't work as expected, since after the zone `await`-s, the Zone appears to have no pending microTask or macroTask (as per `hasTaskState`.

Any idea how to circumvent this limitation?

**Comment by JiaLiPassion** [comment] 2017-04-16 11:11
@elierotenberg , this is a issue, the native async/await behavior break Zone.invoke, I will try to figure out why, thank you for posting the issue.

**Comment by Eugeny** [comment] 2017-04-17 14:59
Thanks. This basically breaks Angular with the Typescript's ES2017 target

**Comment by JiaLiPassion** [comment] 2017-04-18 14:00
@Eugeny , yes, I have post another issue #740, and I will post my research result there.

**Comment by mhevery** [comment] 2017-04-18 16:31
Duplicate of #740.

**Closed by mhevery** 2017-04-18 16:31 UTC
