### ISSUE TITLE
long-stack-trace throws error in InternetExplorer

### ISSUE THREAD

**Issue by Eddman** [angular/zone.js#698] opened 2017-03-24 14:19 UTC
[Error.stack is sometimes `undefined` in IE](https://docs.microsoft.com/en-us/scripting/javascript/reference/stack-property-error-javascript). Therefor Zone fails to call trim method on it:
https://github.com/angular/zone.js/blob/e11d9ff6c7b0f0bb27d0efd49f03d74e47ea48c9/dist/long-stack-trace-zone.js#L70

**Comment by JiaLiPassion** [comment] 2017-03-24 14:21
@Eddman , do you have a reproduce repo? thank you.

**Comment by Eddman** [comment] 2017-03-24 14:29
Well not exactly easy to reproduce. I have 260+ Karma tests and it fails after few minutes. The exception seems to break the whole Karma run. So I'm even not able to detect what test it is.

When I remove `node_modules/zone.js/dist/long-stack-trace-zone.js` from Karma config the tests run without issues....

The application itself seems to work correctly. The only problem is the one test.

**Comment by JiaLiPassion** [comment] 2017-03-24 14:30
@Eddman , could you help to debug the error.originalStack property when the error occurs?

**Comment by Eddman** [comment] 2017-03-24 14:53
Just put there `console.error(error.originalStack);` and the result is:
ERROR: undefined

**Comment by Eddman** [comment] 2017-03-24 15:10
One more: The error that is causing it is:
TypeError{description: 'Unable to get property 'draw' of undefined or null reference', number: -2146823281}

**Comment by JiaLiPassion** [comment] 2017-03-25 15:42
@Eddman, Thank you for the information, if you can provide the error test case code snippet will help, and you are using IE11?

**Comment by Eddman** [comment] 2017-03-27 08:00
You can use the commit linked above. I'm not able to make a smaller scenario. It only fails when all tests are executed.

I'm using IE 11 + Win 7. Please run `npm install` + `grunt testIE`. You need to install `grunt` and `typescript` globally. You also need to uncomment the `long-stack-trace-zone.js` in `karma.conf.js`.

Chrome and FF are running fine.

As polyfill I use `node_modules/core-js/client/shim.js` from `core-js@2.4.1`.

**Comment by JiaLiPassion** [comment] 2017-03-27 08:35
@Eddman , thank you, I will test it.

**Comment by JiaLiPassion** [comment] 2017-03-29 07:22
@Eddman , I tried your repo, but I don't know how to reproduce.

- I confirmed the long-stack-trace is in the karma.conf.js (I didn't uncomment ,because in your repo, the line is not commented)
- I run grunt testIE

this is the result.

<img width="1429" alt="2017-03-29 16 20 25" src="https://cloud.githubusercontent.com/assets/1442575/24443030/eafe3f16-149b-11e7-9532-63adb1bf2a9b.png">

**Comment by vicb** [comment] 2017-03-29 18:14
We see the same issue in Angular test (IE9): https://travis-ci.org/angular/angular/jobs/216434920#L565

**Comment by mhevery** [comment] 2017-03-29 18:16
@JiaLiPassion Could you have a look?

**Comment by JiaLiPassion** [comment] 2017-03-29 18:19
@mhevery, sure, I will check it.

**Comment by Eddman** [comment] 2017-03-30 07:37
@JiaLiPassion Use the commit https://github.com/Deutsche-Boerse-Risk/DAVe-UI/commit/c292aaf4c19d218cd6b300a0fb7e997126bb23cc, not the latest one.

**Comment by JiaLiPassion** [comment] 2017-03-30 08:55
@Eddman, ok, I will try again, you mean checkout the parent commit of your posted one https://github.com/Deutsche-Boerse-Risk/DAVe-UI/commit/764eae9e0829ae3755be972f90ba6f20b926d861 , right, in your post commit, you comment the longstacktrace

**Comment by JiaLiPassion** [comment] 2017-03-30 14:16
@Eddman, I have found the reason, this is a trick one, the reason is because Error.stackTraceLimit is set to 0 in karma-test-shim, I will make a PR to fix it, thank you for your great help.

**Comment by JiaLiPassion** [comment] 2017-04-05 12:52
@vicb, the issue has been fixed in PR #704, in IE9 ,the error.stack is undefined, so with the PR, it will be ok

**Closed** 2017-04-10 09:04 UTC
