### ISSUE TITLE
zone.js v0.8.13 Produces Extensive Zone errors in Unit tests-- 'Unhandled Promise rejection:', 'Cannot create property '__creationTrace__'

### ISSUE THREAD

**Issue by kgentes** [angular/zone.js#832] opened 2017-07-12 21:48 UTC
Using:

- zone.js 0.8.13
- Node 7.10.1
- Angular 4.2.6
- rxjs 5.4.2
- karma 1.7.0
- Typescript 2.3.4

If I use **zone.js 0.8.12** my 111 Client side unit tests  work fine.  After upgrading to **zone.js 0.8.13** I get repeating zone errors as you can see below.

The newest release of zone.js fails extensively on almost all of related Angular unit tests now.  I am seeing this throw two errors:

First one:

```
ERROR: 'Unhandled Promise rejection:', 'Cannot create property '__creationTrace__' on string '__zone_symbol__optimizedZoneEventTask'', '; Zone:', 'ProxyZone', '; Task:', 'Promise.then', '; Value:', TypeError {longStack: 'TypeError: Cannot create property '__creationTrace__' on string '__zone_symbol__optimizedZoneEventTask'
    at Object.onScheduleTask (http://localhost:9876/base/node_modules/zone.js/dist/long-stack-trace-zone.js?76bd579913a209b82c592a4e9924f4696a01ea6f:115:38)
    at ZoneDelegate.scheduleTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?88b6003995efe175b0ecfca3880d4b42eebe4e32:404:51)
    at Object.onScheduleTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?88b6003995efe175b0ecfca3880d4b42eebe4e32:300:29)
    at ZoneDelegate.scheduleTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?88b6003995efe175b0ecfca3880d4b42eebe4e32:404:51)
    at Zone.scheduleTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?88b6003995efe175b0ecfca3880d4b42eebe4e32:235:43)
    at Zone.scheduleEventTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?88b6003995efe175b0ecfca3880d4b42eebe4e32:261:25)
    at HTMLDivElement.addEventListener (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?88b6003995efe175b0ecfca3880d4b42eebe4e32:1561:29)
    at DomEventsPlugin.19.DomEventsPlugin.addEventListener (http://localhost:9876/base/ClientSide/test/panels/panel-output-window/panel-output-window.component.spec.ts?af87a3836823343a258f1bca0af3058ef4b375a6:35817:17)
    at EventManager.19.EventManager.addEventListener (http://localhost:9876/base/ClientSide/test/panels/panel-output-window/panel-output-window.component.spec.ts?af87a3836823343a258f1bca0af3058ef4b375a6:35155:23)
    at DefaultDomRenderer2.19.DefaultDomRenderer2.listen (http://localhost:9876/base/ClientSide/test/panels/panel-output-window/panel-output-window.component.spec.ts?af87a3836823343a258f1bca0af3058ef4b375a6:35676:36)', ngDebugContext: DebugContext_{view: Object{def: ..., parent: ..., viewContainerParent: ..., parentNodeDef: ..., context: ..., component: ..., nodes: ..., state: ..., root: ..., renderer: ..., oldValues: ..., disposables: ...}, nodeIndex: 0, nodeDef: Object{index: ..., parent: ..., renderParent: ..., bindingIndex: ..., outputIndex: ..., flags: ..., childFlags: ..., directChildFlags: ..., childMatchedQueries: ..., matchedQueries: ..., matchedQueryIds: ..., references: ..., ngContentIndex: ..., childCount: ..., bindings: ..., bindingFlags: ..., outputs: ..., element: ..., provider: ..., text: ..., query:..., ngContent: ...}, elDef: Object{index: ..., parent: ..., renderParent: ..., bindingIndex: ..., outputIndex: ..., flags: ..., childFlags: ..., directChildFlags: ..., childMatchedQueries: ..., matchedQueries: ..., matchedQueryIds: ..., references: ..., ngContentIndex: ..., childCount: ..., bindings: ..., bindingFlags: ..., outputs: ..., element: ..., provider: ..., text: ..., query: ..., ngContent: ...}, elView: Object{def: ..., parent: ..., viewContainerParent: ..., parentNodeDef: ..., context: ..., component: ..., nodes: ..., state: ..., root: ..., renderer: ..., oldValues: ..., disposables: ...}}, ngErrorLogger: function () { ... }, __zone_symbol__currentTask: ZoneTask{_zone: Zone{_properties: ..., _parent: ..., _name: ..., _zoneDelegate: ...}, runCount: 0, _zoneDelegates: null, _state: 'notScheduled', type: 'microTask', source: 'Promise.then', data: undefined, scheduleFn: undefined, cancelFn: null, callback: function () { ... }, invoke: function () { ... }}}, 'TypeError: Cannot create property '__creationTrace__' on string '__zone_symbol__optimizedZoneEventTask'
    at Object.onScheduleTask (http://localhost:9876/base/node_modules/zone.js/dist/long-stack-trace-zone.js?76bd579913a209b82c592a4e9924f4696a01ea6f:115:38)
    at ZoneDelegate.scheduleTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?88b6003995efe175b0ecfca3880d4b42eebe4e32:404:51)
    at Object.onScheduleTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?88b6003995efe175b0ecfca3880d4b42eebe4e32:300:29)
    at ZoneDelegate.scheduleTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?88b6003995efe175b0ecfca3880d4b42eebe4e32:404:51)
    at Zone.scheduleTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?88b6003995efe175b0ecfca3880d4b42eebe4e32:235:43)
    at Zone.scheduleEventTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?88b6003995efe175b0ecfca3880d4b42eebe4e32:261:25)
    at HTMLDivElement.addEventListener (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?88b6003995efe175b0ecfca3880d4b42eebe4e32:1561:29)
    at DomEventsPlugin.19.DomEventsPlugin.addEventListener (http://localhost:9876/base/ClientSide/test/panels/panel-output-window/panel-output-window.component.spec.ts?af87a3836823343a258f1bca0af3058ef4b375a6:35817:17)
    at EventManager.19.EventManager.addEventListener (http://localhost:9876/base/ClientSide/test/panels/panel-output-window/panel-output-window.component.spec.ts?af87a3836823343a258f1bca0af3058ef4b375a6:35155:23)
    at DefaultDomRenderer2.19.DefaultDomRenderer2.listen (http://localhost:9876/base/ClientSide/test/panels/panel-output-window/panel-output-window.component.spec.ts?af87a3836823343a258f1bca0af3058ef4b375a6:35676:36)'
```

Second one:

```
Failed: Cannot create property '__creationTrace__' on string '__zone_symbol__optimizedZoneEventTask'
TypeError: Cannot create property '__creationTrace__' on string '__zone_symbol__optimizedZoneEventTask'
	at Object.onScheduleTask (node_modules/zone.js/dist/long-stack-trace-zone.js:115:38)
	at ZoneDelegate.scheduleTask (node_modules/zone.js/dist/zone.js:404:51)
	at Object.onScheduleTask (node_modules/zone.js/dist/zone.js:300:29)
	at ZoneDelegate.scheduleTask (node_modules/zone.js/dist/zone.js:404:51)
	at Zone.scheduleTask (node_modules/zone.js/dist/zone.js:235:43)
	at Zone.scheduleEventTask (node_modules/zone.js/dist/zone.js:261:25)
	at HTMLDivElement.addEventListener (node_modules/zone.js/dist/zone.js:1561:29)
	at DomEventsPlugin.19.DomEventsPlugin.addEventListener (ClientSide/test/panels/panel-output-window/panel-output-window.component.spec.ts:35817:17)
	at EventManager.19.EventManager.addEventListener (ClientSide/test/panels/panel-output-window/panel-output-window.component.spec.ts:35155:23)
	at DefaultDomRenderer2.19.DefaultDomRenderer2.listen (ClientSide/test/panels/panel-output-window/panel-output-window.component.spec.ts:35676:36)
```

**Comment by Toxicable** [comment] 2017-07-12 21:52
Can be reproduce in plunkr here: https://plnkr.co/edit/SNR831sznvMsDjdFJ3MN?p=preview
It happens when you do Event binding.
Property binding is fine

**Comment by kuwas** [comment] 2017-07-12 23:56
I have the same thing when running in Webpack DevServer or unit tests in phantomjs. Works fine when reverting back to `0.8.12` though.

**Comment by JiaLiPassion** [comment] 2017-07-12 23:57
Thank you for posting the issue, I will check it.

**Comment by webdeveloperneeraj** [comment] 2017-07-13 10:22
I am also getting this error using "zone.js": "^0.8.11"

**Comment by pumano** [comment] 2017-07-13 10:49
I got same issues in my tests (angular 4.2.6)

**Comment by guivanrv** [comment] 2017-07-13 11:04
reverting to 0.8.12 does it for now

**Comment by nadavsinai** [comment] 2017-07-13 14:08
@pumano not true unfortunately - I can confirm it does happen on windows

**Comment by Biglr** [comment] 2017-07-13 14:09
Facing the same issue here as well but on Windows using zone.js 0.8.13
Reverting to 0.8.12 for now as suggested above...

**Comment by JiaLiPassion** [comment] 2017-07-13 14:18
sorry for the breaking error, it has been fixed in #834, please wait for the next version.

**Comment by briosheje** [comment] 2017-07-13 14:52
I've had a previous project in another machine working perfectly with zone.js 0.8.5.

Replicated the project today in another machine and, by keeping zone.js version 0.8.5 I'm now experiencing this issue in both testing and regular developing, not sure how it's possible but it looks like it doesn't only affect the latest version. Maybe it's related to other packages aswell?

I'm experiencing the issue in electron, stacktrace is:

```
Unhandled Promise rejection: Cannot create property '__creationTrace__' on string '__zone_symbol__optimizedZoneEventTask' ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot create property '__creationTrace__' on string '__zone_symbol__optimizedZoneEventTask'
    at Object.onScheduleTask (polyfills.js:5032)
    at ZoneDelegate.scheduleTask (polyfills.js:5502)
    at Object.onScheduleTask (polyfills.js:5398)
    at ZoneDelegate.scheduleTask (polyfills.js:5502)
    at Zone.scheduleTask (polyfills.js:5333)
    at Zone.scheduleEventTask (polyfills.js:5359)
    at polyfills.js:6659
    at BrowserPlatformLocation.webpackJsonp.27.BrowserPlatformLocation.onPopState (vendor.js:17581)
    at HashLocationStrategy.webpackJsonp.6.HashLocationStrategy.onPopState (vendor.js:27430)
    at new Location (vendor.js:27219) TypeError: Cannot create property '__creationTrace__' on string '__zone_symbol__optimizedZoneEventTask'
    at Object.onScheduleTask
```

**Comment by guivanrv** [comment] 2017-07-13 14:56
Make sure your package.json does not have '^' before 0.8.5 :)

**Comment by briosheje** [comment] 2017-07-13 14:59
@guivanrv wops, had ^ indeed! Thanks!

**Closed** 2017-07-14 02:59 UTC

**Comment by zskhan** [comment] 2017-07-14 11:38
Fixing zone.js to 0.8.12 fixed my issue too, thank you.
The culprit was indeed 0.8.13

**Comment by cyrilletuzi** [comment] 2017-07-18 09:05
When is the new version planned ? As it's a regression, a quick release just for this would be nice.

**Comment by emilio-martinez** [comment] 2017-07-19 01:53
Haven't updated but I believe v0.8.14 was released earlier today with a fix for this via #834

**Comment by kgentes** [comment] 2017-07-19 04:16
Yes. I can confirm that this is now resolved with the latest release of
zone.js



Kim Gentes / Worship Team LLC

**Comment by mischah** [comment] 2017-07-20 11:33
👌 
It’s released on npm but I was confused that the tag isn’t published and therefore it isn’t on the [GitHub Releases page](https://github.com/angular/zone.js/releases).

**Comment by pumano** [comment] 2017-07-20 11:43
As I understand it released at npm as same version 0.8.13.

**Comment by mischah** [comment] 2017-07-20 11:56
Nope. npm has 0.8.14. See https://www.npmjs.com/package/zone.js

**Comment by agriboz** [comment] 2017-07-20 12:22
the latest version of zone.js handled it perfectly thanks
