### ISSUE TITLE
Cannot set property stack of [object Object] which has only a getter

### ISSUE THREAD

**Issue by D-Thrane** [angular/zone.js#603] opened 2017-01-16 14:12 UTC
"zone.js": "^0.7.2"

`zone.js:704 Uncaught TypeError: Cannot set property stack of [object Object] which has only a getter
    at assignAll (http://localhost:4200/vendor.bundle.js:110081:29)
    at ViewWrappedError.ZoneAwareError (http://localhost:4200/vendor.bundle.js:110152:16)
    at ViewWrappedError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:6953:16)
    at ViewWrappedError.WrappedError [as constructor] (http://localhost:4200/vendor.bundle.js:7015:16)
    at new ViewWrappedError (http://localhost:4200/vendor.bundle.js:58463:16)
    at CompiledTemplate.proxyViewClass.DebugAppView._rethrowWithContext (http://localhost:4200/vendor.bundle.js:82463:23)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:4200/vendor.bundle.js:82436:18)
    at ViewRef_.detectChanges (http://localhost:4200/vendor.bundle.js:59409:20)
    at http://localhost:4200/vendor.bundle.js:39495:67
    at Array.forEach (native)
    at ApplicationRef_.tick (http://localhost:4200/vendor.bundle.js:39495:25)
    at http://localhost:4200/vendor.bundle.js:39414:105
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:109619:26)
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:29171:37)
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:109618:32)`

**Comment by JiaLiPassion** [comment] 2017-01-16 14:13
This is the same with #602, #427, #595, I have made a PR #597 to fix it, please wait for the new release.

**Comment by CristyTarantino** [comment] 2017-01-16 16:41
Yes, imported Highcharts module in my Angular component like this:

```
import * as Highcharts from "highcharts";

import * as HighchartsExporting from "highcharts/modules/exporting";
import * as HighchartsOfflineExporting from "highcharts/modules/offline-exporting";

HighchartsExporting(Highcharts);
HighchartsOfflineExporting(Highcharts);
```

as per https://github.com/gevgeny/angular2-highcharts/issues/126 and I get the same error.

Do you know when you are going to release the new version with this bug fix?

Thank you.

**Comment by JiaLiPassion** [comment] 2017-01-16 22:02
It is under review, it will be released soon.

**Comment by JiaLiPassion** [comment] 2017-01-18 01:32
0.7.6 has been released, please try it.

**Comment by CristyTarantino** [comment] 2017-01-18 11:31
👍  yes all working now. Thank you for being so quick.

**Comment by D-Thrane** [comment] 2017-01-18 12:30
Still get the error with 0.7.6

**Comment by JiaLiPassion** [comment] 2017-01-18 12:39
@D-Thrane,could you provide a reproduce repo or plunker or full stacktrace?

**Comment by D-Thrane** [comment] 2017-01-18 12:56
I'm still new at this. How do I get a full stacktrace?

**Comment by JiaLiPassion** [comment] 2017-01-18 13:16
@D-Thrane  just like you first post in this thread, please copy/paste the error stack trace here, if possible, please put your sample project on github.

**Comment by eurolife** [comment] 2017-01-20 10:20
I did the update to 0.7.6 because I was also getting that error. Now with the update, I don't get that error but I get a different error: Cannot read property 'Title' of undefined. This is happening when I try to display the object returned property of Title in the template.

**Comment by pamtbaau** [comment] 2017-01-20 10:24
Installed zone.js@0.7.6 and error persists. Error occurs on any error in html or typescript.

**Comment by JiaLiPassion** [comment] 2017-01-20 10:25
Please post a reproduce repo ,plunker, or stacktrace.

**Comment by JiaLiPassion** [comment] 2017-01-20 10:34
@eurolife, it seems it is your application's error,could you post your repository or create a plunker?

**Comment by eurolife** [comment] 2017-01-20 11:04
@JiaLiPassion github: https://github.com/eurolife/rfc

**Comment by eurolife** [comment] 2017-01-20 11:47
I found the cause of my undefined error. I needed to give a default value to the variable rfc which is what eventually holds the object.

**Comment by JiaLiPassion** [comment] 2017-01-20 12:52
@eurolife,Great!

**Comment by pamtbaau** [comment] 2017-01-20 13:04
Installing zone.js@0.7.6 did indeed fix the issue of throwing above error on all and any error in own code.
Webpack didn't rebuild libraries based on zone.js@0.7.4.... :-(

**Comment by JiaLiPassion** [comment] 2017-01-20 13:16
@pamtbaau , ok, thank you for the feedback.

**Comment by D-Thrane** [comment] 2017-01-21 18:48
`Uncaught TypeError: Cannot set property stack of [object Object] which has only a getter
    at assignAll (http://localhost:4200/vendor.bundle.js:110081:29)
    at ViewWrappedError.ZoneAwareError (http://localhost:4200/vendor.bundle.js:110152:16)
    at ViewWrappedError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:6953:16)
    at ViewWrappedError.WrappedError [as constructor] (http://localhost:4200/vendor.bundle.js:7015:16)
    at new ViewWrappedError (http://localhost:4200/vendor.bundle.js:58463:16)
    at CompiledTemplate.proxyViewClass.DebugAppView._rethrowWithContext (http://localhost:4200/vendor.bundle.js:82463:23)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:4200/vendor.bundle.js:82436:18)
    at ViewRef_.detectChanges (http://localhost:4200/vendor.bundle.js:59409:20)
    at http://localhost:4200/vendor.bundle.js:39495:67
    at Array.forEach (native)
    at ApplicationRef_.tick (http://localhost:4200/vendor.bundle.js:39495:25)
    at http://localhost:4200/vendor.bundle.js:39414:105
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:109619:26)
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:29171:37)
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:109618:32)`

**Comment by JiaLiPassion** [comment] 2017-01-22 00:54
@D-Thrane, I think you did not update to 0.7.6 successfully, in 0.7.6,assignAll method is removed.Please check the version.

**Comment by D-Thrane** [comment] 2017-01-23 13:23
Had to stop and start my server for it to work. Not I get this:

`Uncaught ViewWrappedError {__zone_symbol__error: Error: Error in ./MapComponent class MapComponent - inline template:11:12 caused by: Invalid argumen…, _nativeError: ZoneAwareError, originalError: InvalidPipeArgumentError, context: DebugContext}__zone_symbol__error: Error: Error in ./MapComponent class MapComponent - inline template:11:12 caused by: Invalid argument 'NaN' for pipe 'DatePipe'
    at ViewWrappedError.ZoneAwareError (http://localhost:4200/vendor.bundle.js:110188:33)
    at ViewWrappedError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:6953:16)
    at ViewWrappedError.WrappedError [as constructor] (http://localhost:4200/vendor.bundle.js:7015:16)
    at new ViewWrappedError (http://localhost:4200/vendor.bundle.js:58463:16)
    at View_MapComponent1.DebugAppView._rethrowWithContext (http://localhost:4200/vendor.bundle.js:82463:23)
    at View_MapComponent1.DebugAppView.detectChanges (http://localhost:4200/vendor.bundle.js:82436:18)
    at ViewContainer.detectChangesInNestedViews (http://localhost:4200/vendor.bundle.js:82570:37)
    at CompiledTemplate.proxyViewClass.View_MapComponent0.detectChangesInternal (/AppModule/MapComponent/component.ngfactory.js:624:14)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:4200/vendor.bundle.js:82238:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:4200/vendor.bundle.js:82433:44)
    at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (http://localhost:4200/vendor.bundle.js:82223:18)
    at CompiledTemplate.proxyViewClass.View_AppComponent0.detectChangesInternal (/AppModule/AppComponent/component.ngfactory.js:78:19)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:4200/vendor.bundle.js:82238:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:4200/vendor.bundle.js:82433:44)
    at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (http://localhost:4200/vendor.bundle.js:82223:18)_nativeError: ZoneAwareErrorcontext: DebugContextmessage: (...)get message: ()set message: (value)name: (...)get name: ()set name: (value)originalError: InvalidPipeArgumentErrororiginalStack: (...)get originalStack: ()set originalStack: (value)stack: (...)get stack: ()set stack: (value)toSource: ()toString: ()zoneAwareStack: (...)get zoneAwareStack: ()set zoneAwareStack: (value)__proto__: WrappedError
Zone.runTask @ zone.js:155
ZoneTask.invoke @ zone.js:345`

**Comment by JiaLiPassion** [comment] 2017-01-23 17:56
@D-Thrane, I think this is the error of your application code, may be you pass some invalid data to model which expect a date format.

**Comment by CognitiveFeedback** [comment] 2017-01-30 22:27
I only needed to set the name-attribute on the input control to fix this problem.
<input type="text" class="form-control" id="phone" [(ngModel)]="phone" **name="phone"**>

**Comment by JiaLiPassion** [comment] 2017-03-29 14:35
@D-Thrane, any update? this issue should be ok now, please close this issue after confirmation.

**Comment by btcioner** [comment] 2017-06-30 09:58
this issue will be in edge，IE 11 is working。

**Comment by JiaLiPassion** [comment] 2019-07-21 14:22
close for now.

**Closed by JiaLiPassion** 2019-07-21 14:22 UTC
