### ISSUE TITLE
Is ZoneAwarePromise really async?

### ISSUE THREAD

**Issue by jscharett** [angular/zone.js#1087] opened 2018-05-09 18:11 UTC
I've encountered an issue which seems to point back to ZoneAwarePromise.  I've created animations for enter/leave to show when a node is added/removed.  These work fine until I do a "move", an remove followed by an add.  I'n debugging my code, I realized my issue was that I was doing the remove+add synchronously, so there was only 1 change detection and hence only 1 animation.  I added a simple timeout like so
```
removeItem();
setTimeout(() => {
    addItem();
});
```
And everything worked.  However, not liking the setTimeout, I replaced it with a Promise and the issue returned
```
removeItem().then(() => {
    addItem();
});
```
Remove items looks something liek this
```
removeItem(): Promise<void> {
    if (itemExists) {
        //Remove item
       return Promise.resolve();
    }
    return Promise.reject();
}
```

I know Promsies are different than setTimeout, but if both are "async", then I am curious as to why the animation fails with a Promise but not a setTimeout?

**Comment by JiaLiPassion** [comment] 2018-05-12 02:31
@jscharett , `Promise.resolve()` is not `async`, it is `sync`, because there is no `async operation` inside. `Promise.resolve().then()` is `async`, because it will schedule a microTask. 

This is the `spec` of `Promise`.

**Comment by JiaLiPassion** [comment] 2018-05-17 02:13
@jscharett , in your example, you use `Promise.resolve()`, not `Promise.resolve().then()`.

**Comment by jscharett** [comment] 2018-05-18 00:16
@JiaLiPassion In my example, I `return Promise.resolve();` of which I then call `.then()` on

**Comment by JiaLiPassion** [comment] 2018-05-18 01:37
@jscharett , ok, then it should work, the behavior should be the same with `setTimeout`, if it is not, could you post a reproduce repo?

**Comment by JiaLiPassion** [comment] 2019-07-21 05:25
I will close this for now.

**Closed by JiaLiPassion** 2019-07-21 05:25 UTC
