### ISSUE TITLE
Calling fetch() with no arguments prevents page from loading when Chrome Developer Tools are open

### ISSUE THREAD

**Issue by pe8ter** [angular/zone.js#439] opened 2016-09-13 17:58 UTC
On [this line](https://github.com/angular/zone.js/blob/master/lib/zone.ts#L1148) there appears to be an on-purpose erroneous call to `fetch()` which normally requires an argument:

    const fetchPromise = global['fetch']();

This error causes the Chrome Developer Tools to pause which means my page won't load. I realize I can turn off the *Pause on Exceptions* flag but then I can't use that feature for my own code. It's not ideal to miss possible exceptions because a dependency forces me to disable this browser feature.

**Comment by Tragetaschen** [comment] 2016-09-14 11:13
Bootstrapping in Edge fails entirely

**Comment by jeffbcross** [comment] 2016-09-14 17:57
Closing as dupe of #436

**Closed by jeffbcross** 2016-09-14 17:57 UTC

**Comment by jramstedt** [comment] 2016-09-15 07:33
I'm still getting paused by this error in 0.6.23 release.

**Comment by pe8ter** [comment] 2016-09-26 21:08
This bug still occurs in Zone.js version 0.6.25, but both this issue and https://github.com/angular/zone.js/issues/436 are closed. Since that issue deals with MS Edge and this one is Chrome-only I think this issue should be reopened.

**Comment by mhevery** [comment] 2016-09-30 21:32
@pe8ter please re-open a new issue with new repro steps, as this repro steps no longer cause the issue.
