### ISSUE TITLE
zone.js 0.8.18 - Protractor tests failed - Timed out waiting for asynchronous Angular tasks

### ISSUE THREAD

**Issue by DosiaKroll** [angular/zone.js#945] opened 2017-10-31 09:11 UTC
We updated version for zone.js from 0.8.12 to 0.8.18. After this, all our e2e tests with Protractor stopped work. When test had to resolve any instructions with expect, finally finished with the same error, ex.:

_Failed: Timed out waiting for asynchronous Angular tasks to finish after 60 seconds. 
This may be because the current page is not an Angular application. Please see the FAQ for more details:
https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular While waiting for 
element with locator - Locator: By(xpath, //div[@id="dashboardBoxes"]/div)_

We checked all versions since 0.8.12 to 0.8.17 and we hadn't issue with them, only with version 0.8.18. We couldn't find any workaround for this, so we're still using version 0.8.17, but if new Angular will be released, then I guess will use the new version of zone.js and our issue with e2e tests will come back.

**Comment by JiaLiPassion** [comment] 2017-10-31 09:21
@DosiaKroll , could you post a reproduce sample? thanks.

**Comment by DosiaKroll** [comment] 2017-10-31 10:17
What do you mean, do you want a complete project or part of configuration ex. protractor.conf.js, or part of a code? I'm asking because this company application, so I can't provide that info and if I create some small app then the issue may not occur because it is random, sometimes issue in the first step of test and sometimes somewhere in the midst of the test.

**Comment by JiaLiPassion** [comment] 2017-10-31 10:20
@DosiaKroll , I want a project which can reproduce this issue, if you can make a sample project which can describe the issue, that will help a lot!

**Comment by DosiaKroll** [comment] 2017-11-07 09:14
I tried to create a sample project for this, but everything is fine. In our general project is too much dependence and too many functionalities which are connected and I can't reproduce the issue in my project.

**Comment by surajbarkale-dolby** [comment] 2017-11-16 08:30
Is there any way to print currently active tasks? I am facing similar issue and I can see that 1 macroTask remains active for 30 seconds after app launch only when executing e2e tests.

**Comment by JiaLiPassion** [comment] 2017-11-16 08:37
@surajbarkale-dolby , it is possible, could you provide a reproduce repo?

**Comment by surajbarkale-dolby** [comment] 2017-11-17 03:06
It turned out to be an issue with Firebase (https://github.com/angular/angularfire2/issues/1345). So, I do not think my issue is related to OP.

**Comment by jooreek** [comment] 2017-11-22 14:56
We have same problem after update to 0.8.18. According to our investigation, it seems to be the same cause as described in #934

**Comment by adrienverge** [comment] 2017-11-29 13:22
For your information, I have the same problem and pull request #935 solves it. Let's hope it can be merged soon!

**Comment by JiaLiPassion** [comment] 2019-07-21 05:59
close for fixed.

**Closed by JiaLiPassion** 2019-07-21 05:59 UTC
