### ISSUE TITLE
Zone.js with formbuilder.online throws Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.

### ISSUE THREAD

**Issue by anikets43** [angular/zone.js#801] opened 2017-06-06 19:36 UTC
Hi Guys,

I'm using form [builder()](http://formbuilder.online/) jquery plugin to generate form in Angular 4.
When I include library  "../node_modules/formBuilder/dist/form-render.min.js" in angular-cli.json, it throws below error.
<img width="1267" alt="screen shot 2017-06-07 at 12 12 01 am" src="https://user-images.githubusercontent.com/7136799/26848190-382c0a0e-4b1d-11e7-9387-20f3d15804d5.png">

I have created a sample to reproduce issue.

[https://github.com/anikets43/ng2-formbuilder.git](url)

Thanks,
Aniket

**Comment by JiaLiPassion** [comment] 2017-06-06 19:48
@anikets43, your reproduce repo's link seems to be broken, please check it.

**Comment by KhaledSMQ** [comment] 2017-08-18 06:54
Hi @anikets43 @JiaLiPassion  have you manage to solve this issue, I have exact problem

**Comment by JiaLiPassion** [comment] 2017-08-18 11:50
there is a walk around is, (I use the https://github.com/anikets43/ng2-formbuilder.git from @anikets43)

remove all `scripts` definitions in `.angluar_cli.json`

```javascript
 "scripts": [
      ],
```

add those scripts to `index.html`

```javascript
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>FormSample</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
 
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <script src="../node_modules/jquery/dist/jquery.js"></script>
  <script src="../node_modules/jquery-ui-sortable/jquery-ui.min.js"></script>
  <script src= "../node_moduiles/formBuilder/dist/form-builder.min.js"></script>
  <script src="../node_modules/formBuilder/dist/form-render.min.js"></script>
</head>
<body>
  <app-root>Loading...</app-root>
</body>
</html>
```

**Comment by KhaledSMQ** [comment] 2017-08-18 21:51
@JiaLiPassion
Thank you , I already manage to transfer the code to typescript, Please feel free to use 

https://github.com/KhaledSMQ/Ng2FormBuilder

**Comment by JiaLiPassion** [comment] 2017-08-19 01:25
@KhaledSMQ , sure, thank you!

**Comment by JiaLiPassion** [comment] 2017-09-17 04:06
the issue has been fixed with #899.

**Comment by alextraul** [comment] 2017-09-25 14:31
@JiaLiPassion so in the interim before the next release, the way to fix this bug would be by hunting down which library is loading the promise polyfill.

**Comment by JiaLiPassion** [comment] 2017-09-25 23:06
@alextraul, yes, you can find the 3rd party promise library, and try to load it before `zone.js`.

**Comment by JiaLiPassion** [comment] 2019-07-21 14:11
Close for now.

**Closed by JiaLiPassion** 2019-07-21 14:11 UTC
